config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  match "home", to: "index#home", :via => 'get'
  match "blog", to: "index#blog", :via => 'get'
  match "gallery", to: "index#gallery", :via => 'get'
  match "about", to: "index#about", :via => 'get'
  match "contact", to: "index#contact", :via => 'get'
  match "winners", to: "index#winners", :via => 'get'
  match "maintenance", to: "index#maintenance", :via => 'get'

  get 'blog/:id', to: 'posts#show', as: 'postlink'
  get 'gallery/:id', to: 'collections#show', as: 'collectionlink'


  

  resources :collections  do
      resources :images 
  end

  resources :posts do
      resources :contents     
  end

  resources :sliders
  devise_for :users

  root 'index#home'

  #get 'form', to: 'messages#new', as: 'form'
  #post 'form', to: 'messages#create'
  post 'contact', to: 'messages#create'

  #Froala editor

  post '/upload_image' => 'upload#upload_image', :as => :froala_upload_image
  post '/delete_image' => 'upload#delete_image', :as => :froala_delete_image
  post '/upload_file' => 'upload#upload_file', :as => :froala_upload_file
  post '/delete_file' => 'upload#delete_file', :as => :froala_delete_file


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord

	has_attached_file :cover, styles: { thumb: "686x464#", large: "1920x1280#"}
	validates_attachment_content_type :cover, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	validates_uniqueness_of :post_id, allow_nil: :true
	validates :title, :presence => true
	validates :subtitle, :presence => true
	validates :cover_file_name, :presence => true

	has_many :images, dependent: :destroy
  	belongs_to :post, optional: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_admin!, except: [:show]
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    #@collections = Collection.all.joins(:post).order("posts.release_date desc")
    @collections = Collection.all.find_by_sql ["SELECT * FROM collections ORDER BY IFNULL((SELECT release_date from posts WHERE posts.id = collections.post_id), created_at) DESC;"]

    ajax_call
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection.images = @collection.images.all

    ajax_call
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collections = Collection.all.joins(:post).order("posts.release_date desc")
    @collection = Collection.new(collection_params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
        format.js   { render :layout => false }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    @collections = Collection.all.joins(:post).order("posts.release_date desc")
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
        format.js   { render :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:post_id, :title, :subtitle, :cover)
    end

    def authenticate_admin!
      unless current_user.present? && current_user.role === 'admin'
        redirect_to new_user_session_path
      end
    end

    def ajax_call
      if request.xhr? # checks whether its an ajax call
        render :layout => false
      else
        respond_to do |format|
          format.html {  }
        end
      end
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_errors.html.erb
<% if @collection.errors.any? %>
	<div id="error_explanation">
		<p><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</p>

		<ul>
			<% @collection.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/collections/_form.html.erb
<%= form_for(@collection, remote: true) do |f| %>
  
    <i class="fa fa-angle-double-up" aria-hidden="true"></i>

    <div class="field">
        <%= f.label :post_id %>
        <%= f.select :post_id, options_for_select(Post.all.map{|p|[p.subtitle, p.id]}, :selected => f.object.post_id), prompt: "Select" %>
    </div>

    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>

    <div class="field">
        <%= f.label :cover %>
        <%= f.file_field :cover %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>

    <div class="collection_errors"><%= render 'errors' %></div>

<% end %>

app/views/collections/_table.html.erb
<div class="collection_grid">
    <% @collections.each do |collection| %>
        <div class="collection_container">
            <%= link_to collectionlink_path(collection), class: "ajaxLink", remote: :true do %>
                <div class="collection">
                    <%= image_tag collection.cover.url(:thumb) %>
                    <div class="overlay_collection">
                      <div class="overlay_content">
                        <h4><%= collection.title %></h4>
                        <span><%= collection.subtitle %></span>
                      </div>
                    </div>
                </div>
            <% end %>
            <% if user_signed_in? && current_user.role ==="admin" %>
                <div class="collection_links">
                    <%= link_to 'Edit', edit_collection_path(collection), :remote => true, class: "collection_edit" %>
                    <%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "collection_delete" %>
                </div>
            <%end%>
        </div>
    <% end %>
    <% if user_signed_in? && current_user.role ==="admin" %>
        <div class="collection_new">
            <td colspan="8"><%= link_to 'New collection', new_collection_path, :remote => true %></td>
        </div>
    <%end%>        
</div>

app/views/collections/create.js.erb
<% if @collection.errors.any? %>
  $('.collection_errors').html("<%= j (render 'errors') %>");
<% else %>
	$(".collection_table").html("<%= j (render 'table') %>");
	$(".collection_form").slideToggle();
	$(".notice").slideToggle().html("Collection created succesfully.").delay(2000).slideToggle();
<% end %>

app/views/collections/destroy.js.erb
$('.collection_delete').bind('ajax:success', function(event) {
	$(".collection_row").remove();
	$(this).closest('.collection_container').fadeOut(1000);
	$(".notice").slideToggle().html("Collection destroyed succesfully.").delay(2000).slideToggle();
	event.stopImmediatePropagation();
});

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<div class="collection_form">		
	<%= render 'form', collection: @collection %>
</div>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/edit.js.erb
$(".collection_clear").val('');
$(function(){
  $(".collection_edit").bind('ajax:complete', function() {
  	$(".collection_form").hide();
  	$(".collection_row").remove();
   	$(this).closest('div').after('<div class="collection_row animationOne"><%= j (render "form") %></div>');
  });
});

app/views/collections/index.html.erb
<div class="collection_table"><%= render 'collections/table' %></div>

<div class="collection_form"></div>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/new.js.erb
//Remover form de editar
$(".edit_collection").each(function(){
    if (!($(this).css('display') === 'none')){
        $(this).slideToggle('normal', function() { $(this).remove(); } );
        $(this).prev().delay(600).fadeIn();
    }
});
$('.collection_new').hide();
$(".collection_form").css("display", "none").html("<%= j (render 'form') %>").slideDown();

app/views/collections/show.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2>Galleria</h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="collection_wrapper">
	<div class="title_container">
		<h1 class="meta_title"><%= title @collection.title %></h1>
		<div class="line"></div>
		<%= image_tag 'gallery.png'%>
	</div>

	<div class="image_table"><%= render "images/table" %></div>

	<div class="image_form"></div>

	<%= link_to 'Ir a Galeria', gallery_path, class: "link ajaxLink", remote: :true %>

	<!-- 	<%= link_to 'Edit', edit_collection_path(@collection) %> -->

</div>

app/views/collections/update.js.erb
<% if @collection.errors.any? %>
  	$(".collection_errors").html("<%= j (render 'errors') %>");
<% else %>
	$(".collection_table").html("<%= j (render 'table') %>");
	$(".notice").slideToggle().html("Collection updated succesfully.").delay(2000).slideToggle();
<% end %>