config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  match "home", to: "index#home", :via => 'get'
  match "blog", to: "index#blog", :via => 'get'
  match "gallery", to: "index#gallery", :via => 'get'
  match "about", to: "index#about", :via => 'get'
  match "contact", to: "index#contact", :via => 'get'
  match "winners", to: "index#winners", :via => 'get'
  match "maintenance", to: "index#maintenance", :via => 'get'

  get 'blog/:id', to: 'posts#show', as: 'postlink'
  get 'gallery/:id', to: 'collections#show', as: 'collectionlink'


  

  resources :collections  do
      resources :images 
  end

  resources :posts do
      resources :contents     
  end

  resources :sliders
  devise_for :users

  root 'index#home'

  #get 'form', to: 'messages#new', as: 'form'
  #post 'form', to: 'messages#create'
  post 'contact', to: 'messages#create'

  #Froala editor

  post '/upload_image' => 'upload#upload_image', :as => :froala_upload_image
  post '/delete_image' => 'upload#delete_image', :as => :froala_delete_image
  post '/upload_file' => 'upload#upload_file', :as => :froala_upload_file
  post '/delete_file' => 'upload#delete_file', :as => :froala_delete_file


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord

	has_attached_file :cover, styles: { thumb: "686x464#", large: "1920x1280#"}
	validates_attachment_content_type :cover, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	validates_uniqueness_of :post_id, allow_nil: :true
	validates :title, :presence => true
	validates :subtitle, :presence => true
	validates :cover_file_name, :presence => true

	has_many :images, dependent: :destroy
  	belongs_to :post, optional: true
end

app/models/content.rb
class Content < ApplicationRecord

	has_attached_file :image, styles: { thumb: "370x250#", large: "1200x800#" }
	validates_attachment_content_type :image, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	default_scope { order(index: :asc) }
	
	validates :index, uniqueness: { scope: :post_id }
	
	belongs_to :post

end

app/models/image.rb
class Image < ApplicationRecord

	has_attached_file :content, styles: { large: "1500x1000#", thumb: "750x500#" }
	validates_attachment_content_type :content, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

  	belongs_to :collection
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/picture.rb
class Picture < ApplicationRecord

	has_attached_file :image, styles: { large: "1400x550#"}
	validates_attachment_content_type :image, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

end

app/models/post.rb
class Post < ApplicationRecord

	has_attached_file :cover, styles: { thumb: "370x250#", large: "1500x400#" }
	validates_attachment_content_type :cover, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	has_many :contents
	accepts_nested_attributes_for :contents

	validates :title, :presence => true
	validates :subtitle, :presence => true
	validates :release_date, :presence => true
	validates :cover_file_name, :presence => true
	validates :author, :presence => true
	
end

app/models/slider.rb
class Slider < ApplicationRecord

	has_attached_file :image, styles: { large: "1920x900#", thumb: "336x123#" }
	validates_attachment_content_type :image, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	default_scope { order(index: :asc) }

	validates_uniqueness_of :index

	validates :title, presence: true

	validates :subtitle, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  before_action :authenticate_user!, only: [:maintenance]
  before_action :authenticate_admin!, only: [:maintenance]

  def home
  	@sliders = Slider.all.order(:index)
  	@posts = Post.all.where("release_date <= ?", Date.today).order(release_date: :desc).limit(9)
  	#@collections = Collection.all.joins(:post).where("posts.release_date <= ?", Date.today).order("posts.release_date desc").limit(6)
    @collections = Collection.all.find_by_sql ["SELECT * FROM collections WHERE (select posts.release_date FROM posts where posts.id = collections.post_id) <= curdate() or post_id IS NULL ORDER BY IFNULL((SELECT release_date from posts WHERE posts.id = collections.post_id), created_at) DESC LIMIT 6;"]
    
    ajax_call
  end

  def blog
  	@posts = Post.all.where("release_date <= ?", Date.today).order(release_date: :desc)

    ajax_call
  end

  def gallery
  	#@collections = Collection.all.joins(:post).where("posts.release_date <= ?", Date.today).order("posts.release_date desc")
    @collections = Collection.all.find_by_sql ["SELECT * FROM collections WHERE (select posts.release_date FROM posts where posts.id = collections.post_id) <= curdate() or post_id IS NULL ORDER BY IFNULL((SELECT release_date from posts WHERE posts.id = collections.post_id), created_at) DESC;"]

    ajax_call
  end

  def about
    @pictures = Picture.all

    ajax_call
  end

  def contact
    @message = Message.new

    ajax_call
  end

  def winners
    ajax_call
  end

  def maintenance
    ajax_call
  end

  private
    def ajax_call
      if request.xhr? # checks whether its an ajax call
        render :layout => false
      else
        respond_to do |format|
          format.html {  }
        end
      end
    end

    def authenticate_admin!
      unless current_user.present? && current_user.role === 'admin'
        redirect_to new_user_session_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/index/about.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Caffora' %></h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="about_container">
	<div class="about">
		<div class="about_info">
			<div>
				<h1>Café</h1>
				<span>Una pasión.</span>
				<p>Costa Rica se caracteriza por ser una región productora de café de categoría de especialidad, esto nos facilita contar con un equipo conformado por baristas consultores especialistas en preparación de café con una amplia experiencia.</p>
			</div>
		</div>
		<div class="about_image">
			<div>
				<%= image_tag 'cafe.jpg'%>
			</div>
		</div>
	</div>
	<div class="about">
		<div class="about_info">
			<div>
				<h1>Arquitectura</h1>
				<span>Los detalles importan.</span>
				<p>El concepto de una cafetería se ve reflejado en el diseño espacial óptimo tanto funcional como estético. Valoramos su idea a través de texturas, colores y sensaciones para lograr completar la experiencia final al degustar un buen café.</p>
			</div>
		</div>
		<div class="about_image">
			<div>
				<%= image_tag 'service_1.jpg'%>
			</div>
		</div>
	</div>
	<div class="about">
		<div class="about_info">
			<div>
				<h1>Fotografía</h1>
				<span>Arte en el café.</span>
				<p>El arte de plasmar detalles en el momento indicado, por eso nos gusta capturar la esencia de cada lugar y taza de café que nos quieran contar una historia de una manera diferente.</p>
			</div>
		</div>
		<div class="about_image">
			<div>
				<%= image_tag 'arq.jpg'%>
			</div>
		</div>
	</div>
</div>
<div class="about_slider">
	<div class="picture_table"><%= render 'pictures/table' %></div>
	<div class="picture_form"></div>
</div>

app/views/index/blog.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Blog' %></h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="title_container">
	<h1>Hablamos sobre Café</h1>
	<div class="line"></div>
	<%= image_tag 'cup_coffe_bean.png'%>
	<div class="subtitle_container">El contar historias con sabor a café, nace a partir de un estilo de vida donde el visitar cafeterías, participar de procesos de preparación de café y documentar cada detalle se volvió un hecho cotidiano, por lo que Caffora nos cuenta de una manera única como disfrutar un mundo inmerso en café. </div>
</div>
<div class="wrapper_blog_posts">
	<div>
		<%= render :file => '/posts/index' %>
	</div>
</div>

app/views/index/contact.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Contacto' %></h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="title_container">
	<h1>Contáctenos</h1>
	<div class="line"></div>
	<%= image_tag 'contact_icon.png'%>
</div>
<div class="contact_wrapper">
	<div class="contact">
		<div class="contact_info">
			<p>Nos encantaría escuchar lo que piensa de nuestro proyecto. No dude en contactarnos si tiene alguna consulta o comentario.</p>
			<span>Heredia, Costa Rica <br>(506) 8814 3107 / <a href="mailto:info@caffora.cafe">info@caffora.cafe</a></span>
			<div class="contact_social_info">
				<div class="contact_social">
					<a href="https://www.facebook.com/caffora/" target="_blank" class="transitionOne">
						<i class="fa fa-facebook"></i>
					</a>
					<a href="https://www.instagram.com/cafforablog/" target="_blank" class="transitionOne">
						<i class="fa fa-instagram"></i>
					</a>
					<a href="https://www.youtube.com/channel/UCHksw5TqiCyqZV26e9zgycQ" target="_blank" class="transitionOne">
						<i class="fa fa-youtube-play"></i>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="contact_form">
		<div class="form">
			<%= render :file => '/messages/new' %>
		</div>
	</div>
</div>

app/views/index/gallery.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Galeria' %></h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="title_container">
	<h1>Arte en el café</h1>
	<div class="line"></div>
	<%= image_tag 'gallery_icon.png'%>
	<div class="subtitle_container">El próceso para que el café llegue a su boca conlleva diversas variables, buscamos mostrarle parte del arte detrás de un ambiente agradable y una deliciosa taza de café.</div>
</div>
<div class="wrapper_gallery_collections">
	<%= render :file => '/collections/index' %>
</div>

app/views/index/home.html.erb
<div class="scroller_container">
	<div class="scroller">
		<% @sliders.each do |slider| %>
	  	<div>
	  		<div class="overlay"></div>
	  		<div class="scroller_content">
	  			<%= image_tag 'icon_slider.png'%>
	  			<h5><%= slider.title %></h5>
	  			<span><%= slider.subtitle %></span>
	  			<% if slider.url.present? %>
	  				<%= link_to "Más Información", slider.url, remote: false %>
	  			<%end%>	
	  		</div>
	  		<%= image_tag slider.image.url(:large) %>
	  	</div>
	  <% end %>
	</div>
</div>	
<div class="wrapper_posts_home">
	<div class="title_container">
		<h1>Publicaciones Recientes</h1>
		<div class="line"></div>
		<%= image_tag 'blog_icon.png'%>
	</div>
	<div>
		<%= render :file => '/posts/index' %>
	</div>
</div>
<div class="parallax_wrapper">
	<div class="parallax">
		<div class="overlay"></div>
		<span class="span_h1">Arte acompañado de una buena taza de café</span>
	</div>
</div>
<div class="wrapper_collections_home">
	<div class="title_container">
		<h1>Galeria de Fotografías.</h1>
		<div class="line"></div>
		<%= image_tag 'home_icon.png'%>
	</div>
	<div>
		<%= render :file => '/collections/index' %>
	</div>
</div>

app/views/index/maintenance.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Mantenimiento' %></h2>
		<div class="page_subtitle">We are Caffora team</div>
	</div>
</div>
<div class="wrapper_maintenance">
	<div class="maintenance">
		<%= link_to sliders_path, class: "ajaxLink", remote: :true do %>
			<i class="fa fa-picture-o" aria-hidden="true"></i>
			<h1>Slider</h1>
		<% end %>
	</div>
	<div class="maintenance">
		<%= link_to posts_path, class: "ajaxLink", remote: :true do %>
			<i class="fa fa-file-text" aria-hidden="true"></i>
			<h1>Post</h1>
		<% end %>
	</div>
	<div class="maintenance">
		<%= link_to collections_path, class: "ajaxLink", remote: :true do %>
			<i class="fa fa-camera" aria-hidden="true"></i>
			<h1>Gallery</h1>
		<% end %>
	</div>
	<div class="maintenance">
		<i class="fa fa-user" aria-hidden="true"></i>
		<h1>Users</h1>
	</div>
</div>

app/views/index/winners.html.erb
<div class="title_page">
	<%= image_tag 'page-title.jpg'%>
	<div class="title_content">
		<h2 class="meta_title"><%= title 'Ganadores del Café' %></h2>
		<div class="page_subtitle">Costa Rica 2017</div>
	</div>
</div>
<div class="wrapper_winners_barismo">
	<div class="title_container_winners">
		<%= image_tag 'logotaza.png'%>
		<h1>Taza de la Excelencia</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
		</ul>
	</div>	
	<div class="title_container_winners">
		<%= image_tag 'logoreto.png'%>
		<h1>Reto Barista</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
			<li><h4>Ariel Bravo - <span>Campeón Nacional</span></h4></li>
			<li><h4>Ricardo Azofeifa - <span>Segundo Puesto</span></h4></li>
			<li><h4>María Elena Rivera - <span>Tercer Puesto</span></h4></li>
		</ul>
	</div>
	<div class="title_container_winners">
		<%= image_tag 'logolatte.png'%>
		<h1>Arte Latte</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
			<li><h4>Francella Rodríguez - <span>Campeón Nacional</span></h4></li>
			<li><h4>Oscar Vargas - <span>Segundo Puesto</span></h4></li>
			<li><h4>Glen Arce - <span>Tercer Puesto</span></h4></li>
		</ul>
	</div>
	<div class="title_container_winners">
		<%= image_tag 'logoinfu.png'%>
		<h1>Infusiones</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
			<li><h4>José Javier Carmona - <span>Campeón Nacional</span></h4></li>
			<li><h4>Alejandro Hoo - <span>Segundo Puesto</span></h4></li>
			<li><h4>Viviana Gómez - <span>Tercer Puesto</span></h4></li>
		</ul>
	</div>
	<div class="title_container_winners">
		<%= image_tag 'logoespi.png'%>
		<h1>Bebida Espirituosa</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
			<li><h4>Sankey Yicarlo - <span>Campeón Nacional</span></h4></li>
			<li><h4>Bruno Rojas - <span>Segundo Puesto</span></h4></li>
			<li><h4>Diego Juárez - <span>Tercer Puesto</span></h4></li>
		</ul>
	</div>
	<div class="title_container_winners">
		<%= image_tag 'logocata.png'%>
		<h1>Catación</h1>
	</div>
	<div class="winners_wrapper">
		<ul>	
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: "Caffora" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Links -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Amaranth:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alice&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
    <!-- Froala Links -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.1/css/froala_editor.pkgd.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.1/css/froala_style.min.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.1//js/froala_editor.pkgd.min.js"></script>
  </head>

  <body class="animation_partial">
    <header>
      <div class="header_static">
      	<div class="header_wrapper">
      		<%= link_to "", root_path, class: 'logo ajaxLink', remote: :true %>
          <div id="menu_mobile"  onclick="showMenu()"><i class="fa fa-bars"></i></div>
    	  	<nav id="menu_classic">
    				<ul >
    					<li> <%= active_link_to "Inicio", root_path, active: :exclusive, remote: :true, class: "ajaxLink" %></li>
    					<li> <%= active_link_to "Blog", blog_path, active: :inclusive, remote: :true, class: "ajaxLink" %></li>
              <li> <%= active_link_to "Galeria", gallery_path, active: :inclusive, remote: :true, class: "ajaxLink" %></li>
              <li> <%= active_link_to "Nosotros", about_path, active: :inclusive, remote: :true, class: "ajaxLink" %></li>
              <li> <%= active_link_to "Contacto", contact_path, active: :inclusive, remote: :true, class: "ajaxLink" %></li>
              <li> <%= active_link_to winners_path, remote: :true, class: "header_icon ajaxLink"  do %><i class="fa fa-trophy" aria-hidden="true"></i><% end %></li>
    				</ul>
    			</nav>
    		</div>
      </div>
      <div class="menu_user">
        <ul>
          <% if user_signed_in? %>
            <li><%= active_link_to destroy_user_session_path, class: "header_icon", method: :delete do %><i class="fa fa-times-circle" aria-hidden="true"></i><% end %></li>
          <%else%>  
            <li><%= active_link_to new_user_session_path, remote: :true, class: "header_icon ajaxLink" do %><i class="fa fa-user-circle" aria-hidden="true"></i><% end %></li>
          <%end%>
          <% if user_signed_in? && current_user.role ==="admin" %> 
            <li><%= active_link_to new_user_registration_path, class: "header_icon" do %><i class="fa fa-user-plus" aria-hidden="true"></i><% end %></li>
            <li><%= active_link_to maintenance_path, remote: :true, class: "header_icon ajaxLink" do %><i class="fa fa-wrench" aria-hidden="true"></i><% end %></li>
          <%end%>
        </ul>
      </div>    
    </header>
    <div>
      <div id="Content">
    	 <%= yield %>
      </div>
      <div class="background_logo animation_partial"></div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <footer>
      <div class="footer_social">
        <a href="https://www.facebook.com/caffora/" target="_blank" class="transitionOne">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="https://www.instagram.com/cafforablog/" target="_blank" class="transitionOne">
          <i class="fa fa-instagram"></i>
        </a>
        <a href="https://www.youtube.com/channel/UCHksw5TqiCyqZV26e9zgycQ" target="_blank" class="transitionOne">
          <i class="fa fa-youtube-play"></i>
        </a>
      </div>
      <div class="footer_info">
        <div>Heredia, Costa Rica / (506) 8814 3107 / <a href="mailto:info@caffora.cafe">info@caffora.cafe</a></div>
        <p>Created by BackyardLinks © 2017 All Rights Reserved</p>
      </div>
    </footer>
  </body>
</html>