config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  match "home", to: "index#home", :via => 'get'
  match "blog", to: "index#blog", :via => 'get'
  match "gallery", to: "index#gallery", :via => 'get'
  match "about", to: "index#about", :via => 'get'
  match "contact", to: "index#contact", :via => 'get'
  match "winners", to: "index#winners", :via => 'get'
  match "maintenance", to: "index#maintenance", :via => 'get'

  get 'blog/:id', to: 'posts#show', as: 'postlink'
  get 'gallery/:id', to: 'collections#show', as: 'collectionlink'


  

  resources :collections  do
      resources :images 
  end

  resources :posts do
      resources :contents     
  end

  resources :sliders
  devise_for :users

  root 'index#home'

  #get 'form', to: 'messages#new', as: 'form'
  #post 'form', to: 'messages#create'
  post 'contact', to: 'messages#create'

  #Froala editor

  post '/upload_image' => 'upload#upload_image', :as => :froala_upload_image
  post '/delete_image' => 'upload#delete_image', :as => :froala_delete_image
  post '/upload_file' => 'upload#upload_file', :as => :froala_upload_file
  post '/delete_file' => 'upload#delete_file', :as => :froala_delete_file


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	has_attached_file :cover, styles: { thumb: "370x250#", large: "1500x400#" }
	validates_attachment_content_type :cover, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	has_many :contents
	accepts_nested_attributes_for :contents

	validates :title, :presence => true
	validates :subtitle, :presence => true
	validates :release_date, :presence => true
	validates :cover_file_name, :presence => true
	validates :author, :presence => true
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_admin!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(release_date: :desc)

    ajax_call
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.contents = @post.contents.all.order(:index)
    @collection = Collection.find_by_post_id(@post.id)

    @post.contents.each do |content|
      if content.style === "Paragraph"
          @page_description = content.body
        break
      end
    end

    ajax_call
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @posts = Post.all.order(release_date: :desc)
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js   { render :layout => false }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @posts = Post.all.order(release_date: :desc)
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js   { render :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :release_date, :cover, :author)
    end

    def authenticate_admin!
      unless current_user.present? && current_user.role === 'admin'
        redirect_to new_user_session_path
      end
    end

    def ajax_call
      if request.xhr? # checks whether its an ajax call
        render :layout => false
      else
        respond_to do |format|
          format.html {  }
        end
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</p>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
    
  <i class="fa fa-angle-double-up" aria-hidden="true"></i>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "post_clear" %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: "post_clear" %>
  </div>

  <div class="field">
    <%= f.label :release_date %>
    <%= f.date_select :release_date, class: "post_clear" %>
  </div>

  <div class="insert">
    <%= f.label :cover %>
    <%= f.file_field :cover, class: "post_clear" %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, class: "post_clear" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <div class="post_errors"><%= render 'errors' %></div>
    
<% end %>

app/views/posts/_table.html.erb
<div class="post_grid">
    <% @posts.each do |post| %>
        <div class="post_container">
            <div class="post">
                <div class="post_thumb">
                    <%= image_tag post.cover.url(:thumb) %>
                </div>
                <h4>
                    <%= link_to post.title, postlink_path(post), class: "transitionOne ajaxLink", remote: :true %>
                </h4>
                <div class="post_details">
                    <span><%= post.release_date.to_formatted_s(:long) %></span>
                    <span>/</span>
                    <span><%= post.subtitle %></span>
                </div>
                <div class="post_view">
                    <%= link_to "Ver post →", postlink_path(post), class: "transitionOne ajaxLink", remote: :true %>
                </div>
                <% if user_signed_in? && current_user.role ==="admin" %>
                    <div class="post_links">
                        <%= link_to 'Edit', edit_post_path(post), :remote => true, class: "post_edit" %>
                        <span>/</span>
                        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "post_delete" %>
                    </div>
                <%end%>   
            </div>
        </div>
    <% end %>
    <% if user_signed_in? && current_user.role ==="admin" %>
        <div class="post_new">
            <td colspan="8"><%= link_to 'New Post', new_post_path, :remote => true %></td>
        </div>
    <%end%>        
</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  	$('.post_errors').html("<%= j (render 'errors') %>");
<% else %>
	$(".post_table").html("<%= j (render 'table') %>");
	$(".post_form").slideToggle();
	$(".notice").slideToggle().html("Post created succesfully.").delay(2000).slideToggle();
<% end %>

app/views/posts/destroy.js.erb
$('.post_delete').bind('ajax:success', function(event) {
	$(".post_row").remove();
	$(this).closest('.post_container').fadeOut(1000);
	$(".notice").slideToggle().html("Post destroyed succesfully.").delay(2000).slideToggle();
	event.stopImmediatePropagation();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<div class="post_form">		
	<%= render 'form', post: @post %>
</div>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="containerOne">

  <div class="post_table"><%= render 'posts/table' %></div>

  <div class="post_form"></div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
//Remover form de editar
$(".edit_post").each(function(){
    if (!($(this).css('display') === 'none')){
        $(this).slideToggle('normal', function() { $(this).remove(); } );
        $(this).prev().delay(600).fadeIn();
    }
});
$('.post_new').hide();
$(".post_form").css("display", "none").html("<%= j (render 'form') %>").slideDown();



app/views/posts/show.html.erb
<div class="post_cover">
	<span class="span_h1"><%= @post.subtitle %></span>
	<%= image_tag @post.cover.url(:large) %>
	<div class="overlay"></div>
</div>

<div class="post_wrapper">
<meta name="title" content="<%= @post.title %>">
	<div class="post_title">
		<h1 class="meta_title"><%= title @post.title %></h1>
		<p><%= @post.release_date.to_formatted_s(:long) %></p>
		<p><span>Escrito por: <%= @post.author %></span></p>
		<a href="https://www.facebook.com/sharer/sharer.php?u=http://caffora.cafe/blog/<%= @post.id %>" class="transitionOne" target="_blank"><i class="fa fa-facebook"></i></a>
	</div>

	<div class="content_table"><%= render "contents/table" %></div>

	<div class="content_form"></div>

</div>
<% if @collection.present? %>
    <div class="parallax_wrapper_post" style="background-image: url(<%= @collection.cover.url(:large)%>)">     
		<div class="parallax_post">
			<div class="overlay"></div>
				<span class="span_h1">Fotografias de <%= @post.subtitle %></span>
			</div>
		</div>
	<div>

		<%= render 'images/table' %>

		<div class="image_form"></div>

		<%= link_to 'Ir al Blog', blog_path, class: "link ajaxLink", remote: :true %>

		<!-- 	<%= link_to 'Edit', edit_post_path(@post) %> -->
	</div>

<% end %>	

app/views/posts/update.js.erb
<% if @post.errors.any? %>
  	$(".post_errors").html("<%= j (render 'errors') %>");
<% else %>
	$(".post_table").html("<%= j (render 'table') %>");
	$(".notice").slideToggle().html("Post updated succesfully.").delay(2000).slideToggle();
<% end %>