config/routes.rb
Rails.application.routes.draw do

  resources :pictures
  match "home", to: "index#home", :via => 'get'
  match "blog", to: "index#blog", :via => 'get'
  match "gallery", to: "index#gallery", :via => 'get'
  match "about", to: "index#about", :via => 'get'
  match "contact", to: "index#contact", :via => 'get'
  match "winners", to: "index#winners", :via => 'get'
  match "maintenance", to: "index#maintenance", :via => 'get'

  get 'blog/:id', to: 'posts#show', as: 'postlink'
  get 'gallery/:id', to: 'collections#show', as: 'collectionlink'


  

  resources :collections  do
      resources :images 
  end

  resources :posts do
      resources :contents     
  end

  resources :sliders
  devise_for :users

  root 'index#home'

  #get 'form', to: 'messages#new', as: 'form'
  #post 'form', to: 'messages#create'
  post 'contact', to: 'messages#create'

  #Froala editor

  post '/upload_image' => 'upload#upload_image', :as => :froala_upload_image
  post '/delete_image' => 'upload#delete_image', :as => :froala_delete_image
  post '/upload_file' => 'upload#upload_file', :as => :froala_upload_file
  post '/delete_file' => 'upload#delete_file', :as => :froala_delete_file


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord

	has_attached_file :content, styles: { large: "1500x1000#", thumb: "750x500#" }
	validates_attachment_content_type :content, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

  	belongs_to :collection
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :set_collection
  # GET /images
  # GET /images.json
  def index
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.collection = @collection
    respond_to do |format|
      if @image.save
        format.html { redirect_to @collection, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
        format.js   { render :layout => false }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
        format.js   { render :layout => false }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to @collection, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    def set_collection
      @collection = Collection.find(params[:collection_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:collection_id, :content)
    end

    def authenticate_admin!
      unless current_user.present? && current_user.role === 'admin'
        redirect_to new_user_session_path
      end
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_errors.html.erb
<% if @image.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

		<ul>
			<% @image.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/images/_form.html.erb
<%= form_for([@collection, @image], remote: true) do |f| %>

  <div class="field">
    <%= f.label :content %>
    <%= f.file_field :content, class: "image_clear" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <div class="images_errors"><%= render 'images/errors' %></div>

<% end %>

app/views/images/_table.html.erb
<div class="image_grid">    
    <div class="cms-grid-wraper cms-grid-masonry shuffle-grid-masonry">
        <div class="row cms-grid cms-grid-masonry">
            <% @collection.images.each do |image| %>
                <div class="cms-grid-item-masonry  cms-grid-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="cms-grid-content overlay_wrap">
                        <%= image_tag image.content.url(:thumb) %>
                        <div class="overlay_collection_images">
                            <div class="overlay_content_images">
                                <a class="icon circle prettyphoto" href="<%= image.content.url(:large)%>" data-rel="prettyPhoto[rel-cms-grid]"><i class="fa fa-hand-pointer-o"></i></a>
                                <a class="icon" href="//pinterest.com/pin/create/button/?url=http://caffora.cafe<%= image.content.url(:large)%>" target="_blank"><i class="fa fa-pinterest"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <% if user_signed_in? && current_user.role ==="admin" %>
                    <div class="image_links">
                        <%= link_to 'Destroy', [@collection, image], method: :delete, data: { confirm: 'Are you sure?' }, class: "image_delete" %>
                    </div>    
                <%end%>
            <% end %>
        </div>
    </div>
    <% if user_signed_in? && current_user.role ==="admin" %>
        <div class="image_new">
            <td colspan="8"><%= link_to 'New Image', new_collection_image_path(@collection), :remote => true, class: "transitionOne buttonOne" %></td>
        </div>
    <%end%>        
</div>

app/views/images/create.js.erb
<% if @image.errors.any? %>
  $('.image_errors').html("<%= j (render 'errors') %>");
<% else %>
	$(".image_clear").val('');
	$(".image_table").html("<%= j (render 'table') %>");
	$(".image_form").html("<p class='image_notice'>Image created succesfully.</p>");
	$(".image_notice").delay(3000).hide(0);
<% end %>

app/views/images/destroy.js.erb
$('.image_delete').bind('ajax:success', function() {
	$(".image_row").remove();
	$(this).closest('.image').fadeOut();
});

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', [@collection, @image] %> |
<%= link_to 'Back', collections_path %>

app/views/images/edit.js.erb
$(".image_clear").val('');
$(function(){
  $(".image_edit").bind('ajax:complete', function() {
  	$(".image_form").hide();
  	$(".image_row").remove();
   	$(this).closest('div').after('<div class="image_row animationOne"><%= j (render form") %></div>');
  });
});

app/views/images/index.html.erb
<div class="images_wrapper">

  <div class="image_table"><%= render 'table' %></div>

  <div class="image_form"></div>

</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', collection_path(@collection) %>

app/views/images/new.js.erb
$(".image_row").remove();
$(".image_form").show();
$(".image_form").html("<%= j (render 'form') %>");

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= image_tag @image.content.url(:large) %>
</p>

<%= link_to 'Edit', edit_collection_image_path(@collection, @image) %> |
<%= link_to 'Back', collection_path(@collection) %>

app/views/images/update.js.erb
<% if @image.errors.any? %>
  $(".image_errors").html("<%= j (render 'errors') %>");
<% else %>
	$(".image_clear").val('');
	$('.image_table').html("<%= j (render 'table') %>");
	$(".image_form").show();
	$(".image_form").html("<p class='notice'>Image updated succesfully.</p>");
	$(".image_form").delay(3000).hide(0);
<% end %>